In [17]:
import numpy as np

# Define the weights and biases
# Use the previously defined weight and bias matrices
W1 = np.array([
    [1, 1, 1, 1],
    [1, 1, 2, 1],
    [1, 1, 1, 1]
], dtype=float)

b1 = np.array([1, 1, 1], dtype=float)

W2 = np.array([
    [1, 4, 1],
    [1, 1, 1]
], dtype=float)

b2 = np.array([1, 1], dtype=float)

W3 = np.array([
    [1, 1],
    [3, 1],
    [1, 1]
], dtype=float)

b3 = np.array([1, 1, 1], dtype=float)

# Define the activation function and its derivative
def activation(x):
    return np.tanh(0.5 * x - 2)


def activation_derivative(x):
    return 0.5 * (1 - np.tanh(0.5 * x - 2) ** 2)


# Training data and targets
X_train = np.array([
   [1,1,1,1],
   [1,0,0,-1]
], dtype=float)

# Target values for class B and class A
target_B = np.array([-1,1,-1], dtype=float)
target_A = np.array([1,-1,-1], dtype=float)

# Learning rate
learning_rate = 0.1

# Number of training examples
num_examples = X_train.shape[0]
# Lists to store errors
errors_B = []
errors_A = []

grad3 = 0
grad2 = 0
grad1 = 0
delta3_s = 0
delta2_s = 0
delta1_s = 0

# Forward and backward propagation
for i in range(num_examples):
    # Forward propagation
    x = X_train[i]
    z1 = np.dot(W1, x) + b1
    #print("z1: ", z1)
    a1 = activation(z1)
    #print("a1: ", a1)
    z2 = np.dot(W2, a1) + b2
    #print("z2: ", z2)
    a2 = activation(z2)
    #print("a2: ", a2)
    z3 = np.dot(W3, a2) + b3
    #print("z3: ", z3)
    a3 = activation(z3)
    #print("a3: ", a3)

    # Calculate the error for the specific target   
    error = a3 - target_B if i == 0 else a3 - target_A
    #print("error: ", error)
    if i == 0:
        errors_B.append(error)
    else:
        errors_A.append(error)

    # Backward propagation
    delta3 = error * activation_derivative(z3)
    #print("delta3:", delta3)
    delta2 = np.dot(W3.T, delta3) * activation_derivative(z2)
    #print("delta2:", delta2)
    delta1 = np.dot(W2.T, delta2) * activation_derivative(z1)
    #print("delta1:", delta1)

    delta3_s += delta3
    delta2_s += delta2
    delta1_s += delta1



    grad3 += np.outer(delta3, a2)
    #print("\n\n\n\n\n\ngrad3: ", grad3, "\n\n")
    grad2 += np.outer(delta2, a1)
    #print("grad2: ", grad2, "\n\n")
    grad1 += np.outer(delta1, x)
    #print("grad1: ", grad1, "\n\n\n\n\n\n\n")

    # Update weights and biases
W3 -= learning_rate * grad3
b3 -= learning_rate * delta3_s
W2 -= learning_rate * grad2
b2 -= learning_rate * delta2_s
W1 -= learning_rate * grad1
b1 -= learning_rate * delta1_s


# Print updated weights and biases
print("Updated W1:\n", W1)
print("Updated b1:\n", b1)
print("Updated W2:\n", W2)
print("Updated b2:\n", b2)
print("Updated W3:\n", W3)
print("Updated b3:\n", b3)

# Calculate and print the errors
error_B = 0.5 * np.linalg.norm(np.array(errors_B))**2
error_A = 0.5 * np.linalg.norm(np.array(errors_A))**2

print("Error for class B:", error_B)
print("Error for class A:", error_A)



Updated W1:
 [[1.0187207  1.01871904 1.01871904 1.01871737]
 [1.03358917 1.03358719 2.03358719 1.03358521]
 [1.0187207  1.01871904 1.01871904 1.01871737]]
Updated b1:
 [1.0187207  1.03358917 1.0187207 ]
Updated W2:
 [[1.01730444 4.02851932 1.01730444]
 [1.00467751 1.00771893 1.00467751]]
Updated b2:
 [1.0374494  1.01017306]
Updated W3:
 [[0.99703633 0.9977484 ]
 [3.01431372 0.98168546]
 [0.99971282 1.00040847]]
Updated b3:
 [1.00198208 1.03177312 0.99930442]
Error for class B: 1.6359762799940256
Error for class A: 1.9732250813745849
